### ISSUE TITLE
differences compared to other indent-detection packages?

### ISSUE THREAD

**Issue by stevengj** [JunoLab/atom-indent-detective#1]
There are also packages `auto-detect-indentation`, and `guess-indent` ... which one should I use?  The README provides no clue regarding what the advantage of this package over the others is.

**Comment by raffomania** [comment]
This package worked more reliably for me than `auto-detect-indentation`

**Comment by parasyte** [comment]
`auto-detect-indentation` is now 2 years out of date, and no longer working at all on recent version of Atom. This package saved the day!
