### ISSUE TITLE
Fails to detect default indentation

### ISSUE THREAD

**Issue by msrd0** [JunoLab/atom-indent-detective#10]
Every time I create a new file in Atom (so indent-detective is unable to detect my current indentation), it selects `Spaces(4)`. However, in my editor settings in Atom I have selected a Tab Length of 4, no Soft Tabs, and a Tab Type of hard. So the correct default setting would be `Tabs`.

## Expected behaviour

The package should use `Tabs` as my default for newly created files.

## Actual behaviour

The package ignores my settings and chooses `Spaces(4)`.

## Package version

0.3.1

## Atom version

```
Atom    : 1.33.1
Electron: 3.0.13
Chrome  : 66.0.3359.181
Node    : 10.2.0
```

## pacman's information

```
Name            : atom
Version         : 1.33.1-3
Description     : A hackable text editor for the 21st Century
Architecture    : x86_64
URL             : https://github.com/atom/atom
Licenses        : MIT  custom
Groups          : None
Provides        : None
Depends On      : apm  electron  libxkbfile
Optional Deps   : ctags: symbol indexing support
                  git: Git and GitHub integration [installed]
Required By     : None
Optional For    : None
Conflicts With   : None
Replaces        : atom-editor
Installed Size  : 182.43 MiB
Packager        : Nicola Squartini <tensor5@gmail.com>
Build Date      : So 30 Dez 2018 19:07:24 CET
Install Date    : Sa 05 Jan 2019 16:54:22 CET
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature
```

**Comment by pfitzseb** [comment]
Fixed in 0.3.2 (was just a stupid typo that a linter would've caught had I bothered to run one...).
Thanks for the report! :)
