### ISSUE TITLE
Doesn't detect indentation in files restored from previous session on launch

### ISSUE THREAD

**Issue by sryze** [JunoLab/atom-indent-detective#11]
First of all, thanks for creating this extension (the other one for detecting indentation appears to be broken/unmaintained).

I would like to report an issue with Atom 1.34 (on Linux, if that matters). If I open a file manually indentation is detected correctly, everything works great. However, if I close Atom and start it again, the extension doesn't re-detect indentation settings in files that are reopened by Atom automatically. If I close and reopen the same file, it works again. It would be nice to have indentation detection work in such cases as well.

**Comment by pfitzseb** [comment]
This is almost fixed now -- the only case where we're not correctly detecting the indentation on startup is the active file (although that's corrected as soon as you type, so not too big a deal). Also, all text editors should have the correct indentation settings as soon as you switch to them, so switching away from that restored active text editor and back to it will fix the detection as well.
